title: Ursa Robotics
description: Η σελίδα για το Project 'Έξυπνο Σπίτι' του 1ου ΕΠΑ.Λ. Πρέβεζας 
theme: jekyll-theme-minimal
show_downloads: false
github.is_user_page: false
github.is_project_page: false
